In [1]:
import numpy as np

# Simulated transaction data (each row: a transaction)
# Columns: [Amount ($), Time (24-hour format), Merchant ID]
transactions = np.array([
    [4500, 14, 101],  # Normal
    [6000, 22, 202],  # Large amount & outside business hours
    [200, 3, 303],    # Outside business hours
    [7500, 10, 404],  # Large amount
    [4000, 23, 101],  # Outside business hours
    [9000, 5, 202],   # Large amount & outside business hours
    [100, 20, 505]    # Normal transaction
])

# Define fraud detection conditions
high_amount = transactions[:, 0] > 5000  # Amount > $5,000
print(f"high_amount = {high_amount}")
outside_business_hours = (transactions[:, 1] < 6) | (transactions[:, 1] > 21)  # Time < 6 AM OR Time > 9 PM
print(f"outsdie_hours = {outside_business_hours}")
blocked_merchants = np.isin(transactions[:, 2], [202, 303])  # Merchant ID in the blocked list
print(f"blocked_merchants = {blocked_merchants}")
# Identify suspicious transactions (meeting at least 2 fraud conditions)
potential_fraud = (high_amount & outside_business_hours) | (high_amount & blocked_merchants) | (outside_business_hours & blocked_merchants)
print(f"potential_fraud = {potential_fraud}")
# Print results
print("Suspicious Transactions (Flagged as Fraud):")
print(transactions[potential_fraud])


high_amount = [False  True False  True False  True False]
outsdie_hours = [False  True  True False  True  True False]
blocked_merchants = [False  True  True False False  True False]
potential_fraud = [False  True  True False False  True False]
Suspicious Transactions (Flagged as Fraud):
[[6000   22  202]
 [ 200    3  303]
 [9000    5  202]]


In [1]:
import numpy as np

# Simulated inventory data (each row: a product)
# Columns: [Current Stock, Weekly Demand Projection]
inventory = np.array([
    [50, 30],   # OK (Stock is sufficient)
    [10, 60],   # Needs restocking (Low stock & High demand)
    [25, 45],   # Needs restocking (High demand and not enough stock)
    [15, 70],   # Needs restocking (Low stock & High demand)
    [5, 90],    # Needs urgent restocking (Almost empty & High demand)
    [40, 35]    # OK (Stock is sufficient)
])

# Define restocking conditions
low_stock = inventory[:, 0] < 20  # Current stock < 20
high_demand = inventory[:, 1] > 50  # Projected demand > 50
critical_shortage = (inventory[:, 0] - inventory[:, 1]) < 10  # Stock after demand < 10

# Identify products needing urgent restocking
urgent_restock = low_stock & high_demand & critical_shortage

# Print results
print("Products that need urgent restocking:")
print(inventory[urgent_restock])


Products that need urgent restocking:
[[10 60]
 [15 70]
 [ 5 90]]


In [9]:
import numpy as np

# Simulated daily power usage (kWh) for different households (rows: households, cols: days)
daily_power_usage = np.array([
    [15, 18, 20, 22, 25, 30, 28],  # Household 1
    [35, 38, 40, 45, 50, 48, 42],  # Household 2
    [8, 10, 12, 15, 10, 8, 9],     # Household 3
    [50, 55, 60, 65, 70, 75, 80]   # Household 4 (High user)
])

# 1. Calculate total monthly consumption (30 days)
monthly_power_usage = np.sum(daily_power_usage, axis=1) * (30 / 7)  # Sum over days, scale to 30 days
print("Monthly Power Consumption (kWh):", monthly_power_usage)

# 2. Compute power wastage (assume efficiency threshold of 800 kWh per month)
efficiency_threshold = 800
power_wastage = np.maximum(monthly_power_usage - efficiency_threshold, 0)
print("Power Wastage (kWh):", power_wastage)

# 3. Apply tiered pricing per kWh
standard_rate = 0.12
medium_rate = 0.15
high_rate = 0.20

# Apply pricing logic
low_usage = monthly_power_usage < 500
medium_usage = (monthly_power_usage >= 500) & (monthly_power_usage <= 1000)
high_usage = monthly_power_usage > 1000

# Compute energy bill based on tiered pricing
energy_bill = (monthly_power_usage * standard_rate * low_usage) + \
              (monthly_power_usage * medium_rate * medium_usage) + \
              (monthly_power_usage * high_rate * high_usage)

print("Energy Bills ($):", energy_bill)

# 4. Calculate energy efficiency score using logarithm (lower is better)
efficiency_score = np.log1p(monthly_power_usage)  # log(1 + usage) prevents log(0)
print("Energy Efficiency Score:", efficiency_score)


Monthly Power Consumption (kWh): [ 677.14285714 1277.14285714  308.57142857 1950.        ]
Power Wastage (kWh): [   0.          477.14285714    0.         1150.        ]
Energy Bills ($): [101.57142857 255.42857143  37.02857143 390.        ]
Energy Efficiency Score: [6.51935797 7.15316341 5.73518885 7.57609734]


In [9]:
import numpy as np

# Simulated daily power usage (kWh) for different households (rows: households, cols: days)
daily_power_usage = np.array([
    [15, 18, 20, 22, 25, 30, 28],  # Household 1
    [35, 38, 40, 45, 50, 48, 42],  # Household 2
    [8, 10, 12, 15, 10, 8, 9],     # Household 3
    [50, 55, 60, 65, 70, 75, 80]   # Household 4 (High user)
])

# 1. Calculate total monthly consumption (30 days)
monthly_power_usage = np.sum(daily_power_usage, axis=1) * (30 / 7)  # Sum over days, scale to 30 days
print("Monthly Power Consumption (kWh):", monthly_power_usage)

# 2. Compute power wastage (assume efficiency threshold of 800 kWh per month)
efficiency_threshold = 800
power_wastage = np.maximum(monthly_power_usage - efficiency_threshold, 0)
print("Power Wastage (kWh):", power_wastage)

# 3. Apply tiered pricing per kWh
standard_rate = 0.12
medium_rate = 0.15
high_rate = 0.20

# Apply pricing logic
low_usage = monthly_power_usage < 500
medium_usage = (monthly_power_usage >= 500) & (monthly_power_usage <= 1000)
high_usage = monthly_power_usage > 1000

# Compute energy bill based on tiered pricing
energy_bill = (monthly_power_usage * standard_rate * low_usage) + \
              (monthly_power_usage * medium_rate * medium_usage) + \
              (monthly_power_usage * high_rate * high_usage)

print("Energy Bills ($):", energy_bill)

# 4. Calculate energy efficiency score using logarithm (lower is better)
efficiency_score = np.log1p(monthly_power_usage)  # log(1 + usage) prevents log(0)
print("Energy Efficiency Score:", efficiency_score)


Monthly Power Consumption (kWh): [ 677.14285714 1277.14285714  308.57142857 1950.        ]
Power Wastage (kWh): [   0.          477.14285714    0.         1150.        ]
Energy Bills ($): [101.57142857 255.42857143  37.02857143 390.        ]
Energy Efficiency Score: [6.51935797 7.15316341 5.73518885 7.57609734]


In [ ]:
from pyspark.ml import Pipeline
from pyspark.ml.classification import LogisticRegression
from pyspark.ml.feature import VectorAssembler

# Define pipeline stages
assembler = VectorAssembler(inputCols=["feature1", "feature2"], outputCol="features")
lr = LogisticRegression(featuresCol="features", labelCol="label")
pipeline = Pipeline(stages=[assembler, lr])
